# Generated by Django 5.2.6 on 2025-09-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catagory',
            field=models.CharField(default='Techonology', max_length=100),
            preserve_default=False,
        ),
    ]
