# Generated by Django 5.2.6 on 2025-09-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(default='images\\Django deploy.webp', max_length=100),
            preserve_default=False,
        ),
    ]
